**VECTOR DAN VEKTOR TRANSPOSISI**

In [1]:
import numpy as np

In [2]:
# Soal 7.1 - Buat vector x dengan ukuran 3x1
x = np.array([103, 10, 3]) # type argument is optional, e.g.: dtype=np.float16
x

array([103,  10,   3])

In [3]:
# Hitung panjang vector x
len(x)

3

In [4]:
# Tampilkan ukuran vector x
x.shape

(3,)

In [5]:
# Tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [6]:
# Akses elemen pertama dari vector x
x[0] # zero-indexed

np.int64(103)

In [7]:
# Tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [8]:
# Soal 7.2 - Lakukan transpose pada vector x dan simpan pada variabel x_t
# Transposing a regular 1-D array has no effect...
x_t = x.T
x_t

array([103,  10,   3])

In [9]:
# Tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [11]:
# Lakukan transpose pada vector y dan simpan pada variabel y_t
# ...but it does we use nested "matrix-style" brackets:
y = np.array([[103, 10, 3]])
y

array([[103,  10,   3]])

In [12]:
y.shape

(1, 3)

In [13]:
# ...but can transpose a matrix with a dimension of length 1, which is mathematically equivalent:
y_t = y.T
y_t

array([[103],
       [ 10],
       [  3]])

In [14]:
# Tampilkan ukuran dari vector y_t
y_t.shape # this is a column vector as it has 3 rows and 1 column

(3, 1)

In [15]:
# Column vector dapat di-transpose kembali ke row vector semula:
y_t.T

array([[103,  10,   3]])

In [16]:
y_t.T.shape

(1, 3)

In [17]:
# Soal 7.3 - Lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf

In [19]:
# Buat vector x menggunakan pytorch
x_pt = torch.tensor([103, 10, 3])
x_pt

tensor([103,  10,   3])

In [20]:
# Transpose vector x menggunakan pytorch
x_pt_t = x_pt.reshape(1, -1).T
x_pt_t

tensor([[103],
        [ 10],
        [  3]])

In [21]:
x_pt_t.shape

torch.Size([3, 1])

In [22]:
# Buat vector x menggunakan tensorflow
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

In [23]:
# Transpose vector x menggunakan tensorflow
x_tf_t = tf.transpose(tf.expand_dims(x_tf, 0))
x_tf_t

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[25],
       [ 2],
       [ 5]], dtype=int32)>

In [24]:
x_tf_t.shape

TensorShape([3, 1])

**NORMS AND UNIT VECTORS (L2 NORMS)**

In [25]:
import numpy as np

In [27]:
# Soal 8.1 - Buat vector x dengan ukuran 3x1
x = np.array([103, 10, 3]) # type argument is optional, e.g.: dtype=np.float16
x

array([103,  10,   3])

In [28]:
# Hitung nilai L2 norm dari vector x
np.linalg.norm(x)

np.float64(103.52777405121778)

In [29]:
# Soal 8.2 - Buat vector v dengan elemen (3, 4)
v = np.array([3, 4])
v

array([3, 4])

In [30]:
# Hitung nilai L2 norm dari vector v
np.linalg.norm(v)

np.float64(5.0)

In [31]:
# Tampilkan unit vector dari vector v
v_unit = v / np.linalg.norm(v)
v_unit

array([0.6, 0.8])

In [32]:
# Hitung panjang unit vector dari vector v
np.linalg.norm(v_unit)

np.float64(1.0)

**BASIS, ORTHOGONAL, AND ORTHONORMAL VECTORS**

In [33]:
import numpy as np

In [34]:
# Soal 9.1 - Buat vector i dengan elemen (1,0) dan vector j dengan elemen (0,1)
i = np.array([1, 0])
i

array([1, 0])

In [35]:
j = np.array([0, 1])
j

array([0, 1])

In [36]:
# Buktikan bahwa vector i dan vector j itu orthogonal
np.dot(i, j) # detail on the dot operation coming up...

np.int64(0)

In [37]:
# Soal 9.2 - Bagaimana dengan v=(1,2) dan w=(2,-1), apakah juga orthogonal?
v = np.array([1, 2])
v

array([1, 2])

In [38]:
w = np.array([2, -1])
w

array([ 2, -1])

In [39]:
np.dot(v, w) # jika hasil dot product = 0, maka vector v dan w orthogonal

np.int64(0)

**MATRIX TENSOR**

In [40]:
import numpy as np

In [42]:
# Soal 10.1 - Buat matrix X berukuran 2x3 menggunakan numpy
# Use array() with nested brackets:
X = np.array([[25, 1], [5, 6], [11, 3]])
X

array([[25,  1],
       [ 5,  6],
       [11,  3]])

In [43]:
# Tampilkan ukuran dari matrix X
X.shape

(3, 2)

In [44]:
# Tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0] # Select left column of matrix X (zero-indexed)

array([25,  5, 11])

In [45]:
# Tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:] # Select middle row of matrix X

array([5, 6])

In [46]:
import torch

In [47]:
# Soal 10.2 - Ulangi soal nomor 1 menggunakan pytorch
X_pt = torch.tensor([[25, 1], [5, 6], [11, 3]])
X_pt

tensor([[25,  1],
        [ 5,  6],
        [11,  3]])

In [48]:
X_pt.shape # pythonic relative to TensorFlow

torch.Size([3, 2])

In [49]:
X_pt[:,0] # Select left column

tensor([25,  5, 11])

In [50]:
X_pt[1,:] # N.B.: Python is zero-indexed; written algebra is one-indexed

tensor([5, 6])

In [51]:
import tensorflow as tf

In [52]:
# Ulangi soal nomor 1 menggunakan tensorflow
X_tf = tf.Variable([[25, 1], [5, 6], [11, 3]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  1],
       [ 5,  6],
       [11,  3]], dtype=int32)>

In [53]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [54]:
X_tf[:,0] # Select left column

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25,  5, 11], dtype=int32)>

In [55]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>

**GENERIC TENSOR NOTATION**

In [56]:
import torch
import tensorflow as tf

In [57]:
# Soal 11.1 - Jelaskan tentang perintah ini:
# images_pt = torch.zeros([25, 15, 61, 13])
# Perintah ini membuat tensor rank 4 berisi nilai nol dengan dimensi:
# - 32 : jumlah gambar dalam training batch
# - 28 : tinggi gambar dalam piksel
# - 28 : lebar gambar dalam piksel
# - 3  : jumlah channel warna (RGB) untuk gambar berwarna penuh
images_pt = torch.zeros([25, 15, 61, 13])

In [58]:
images_pt

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         ...,

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 

In [60]:
images_tf = tf.zeros([25, 15, 61, 13])

In [61]:
images_tf

<tf.Tensor: shape=(25, 15, 61, 13), dtype=float32, numpy=
array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ...,

**Exercises on Algebra Data Structures**

In [62]:
import numpy as np

In [63]:
# Soal 12.1 - Selesaikan soal berikut
# 1. What is the transpose of this vector?
# [25, 2, -3, -23]
v = np.array([[25, 2, -3, -23]])
v

array([[ 25,   2,  -3, -23]])

In [64]:
v.shape

(1, 4)

In [65]:
# Transpose vector v
v_t = v.T
v_t

array([[ 25],
       [  2],
       [ -3],
       [-23]])

In [66]:
v_t.shape

(4, 1)